DROP TABLE IF EXISTS watchlist CASCADE;

CREATE TABLE watchlist (
    id SERIAL PRIMARY KEY NOT NULL,
    users_id INTEGER REFERENCES users(id) NOT NULL ON DELETE CASCADE,
    tvshow_id INTEGER REFERENCES users(id) NOT NULL ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL
);
