DROP TABLE IF EXISTS likes CASCADE;

CREATE TABLE likes (
    id SERIAL PRIMARY KEY NOT NULL,
    posts_id INTEGER REFERENCES posts(id) NOT NULL ON DELETE CASCADE,
    users_id INTEGER REFERENCES users(id) NOT NULL ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL
);
