DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE comments (
    id SERIAL PRIMARY KEY NOT NULL,
    text TEXT NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    tvshow_id INTEGER REFERENCES tvshows(id) ON DELETE CASCADE
);
