DROP TABLE IF EXISTS user_tvshows CASCADE;

CREATE TABLE user_tvshows (
    id SERIAL PRIMARY KEY NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    tvshow_id INTEGER REFERENCES tvshows(id) ON DELETE CASCADE
);
